### ISSUE TITLE
Question - differences

### ISSUE THREAD

**Issue by inxomnyaa** [jasonwynn10/ThePermissionManager#1]
I am interested. What are the differences to PurePerms? Is this more user friendly? What are the features and planned features?

**Comment by jasonw4331** [comment]
So far, the only difference is how easily the code can be read. I have started work on adding different providers to manage the players' data and various commands to work with the said data as well.
I plan to add multiworld support and permission expirations in the future. I'm also looking for other features to add.

**Comment by jasonw4331** [comment]
I also have client-side command syntax checks which pureperms doesn't currently have.

**Comment by inxomnyaa** [comment]
Which - sadly - won't work in 1.2 ;)

Messing around with 1.2 currently, pmmp doesnt support command suggestions anymore, its not json/an array anymore but some bytearray stuff.

Sounds great anyways, does it autocomplete permissions in 1.1?

**Comment by jasonw4331** [comment]
Permissions do autofill in 1.1 and I haven't had any problems with it yet. The only issue I currently have is that none of the commands work on the console...?
